// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XLAB_TASK.Models
{
    [Table("Invoice")]
    public partial class Invoice
    {
        public Invoice()
        {
            Invoice_Details = new HashSet<Invoice_Detail>();
        }

        [Key]
        public short id { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string customerName { get; set; }
        [Column(TypeName = "date")]
        public DateTime? date { get; set; }

        [InverseProperty("invoice")]
        public virtual ICollection<Invoice_Detail> Invoice_Details { get; set; }
    }
}