// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace XLAB_TASK.Models
{
    public partial class Invoice_Detail
    {
        [Key]
        [StringLength(50)]
        [Unicode(false)]
        public string itemName { get; set; }
        [Key]
        public short invoiceId { get; set; }
        public short itemQty { get; set; }
        [Column(TypeName = "smallmoney")]
        public decimal itemPrice { get; set; }
        [Column(TypeName = "money")]
        public decimal itemTotalPrice { get; set; }

        [ForeignKey("invoiceId")]
        [InverseProperty("Invoice_Details")]
        public virtual Invoice invoice { get; set; }
    }
}